# -*- coding: utf-8 -*-
"""16EylulPythonGiris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bXvcfKdLbnQYy7Zp3MqafM_PmNOlYbm

# **CASE-1**
"""

"""
SORU-1
Ekrana Yazı Yazdırma (print)
Ekrana "Python öğreniyorum" yazdıran bir kod yazın.
Adınızı ve soyadınızı aynı print satırında yazdırın.
Ekrana önce bir sayı, sonra bir yazı yazdıran iki ayrı print satırı yazın.
"""
print("Python Öğreniyorum")
print("Eren Altun")
print(23)
print("yaşındayım")

"""
SORU-2
Yorum Satırları
Bir satır kod yazın ve yanına o satırın ne işe yaradığını açıklayan bir yorum ekleyin.
Çok satırlı bir yorum kullanarak adınızı, yaşınızı ve şehrinizi not edin (kod çalıştırılmadan).
"""
print("Eren Altun",23)

#Eren Altun , 23 yaşındayım. İstanbulda yaşamaktayım.

"""
SORU-3
Değişkenler
sehir adında bir değişken oluşturup içine yaşadığınız şehri atayın ve yazdırın.
puan adında bir değişkene 50 değerini verin, sonra değerini 75 olarak güncelleyip her iki değeri de yazdırın.
"""

sehir="İstanbul"
print(sehir)
puan=50
print(puan)
puan=75
print(puan)

"""
SORU-4
Veri Tipleri
Bir tam sayı, bir ondalıklı sayı, bir yazı ve bir boolean değişken oluşturup her birinin tipini type() ile yazdırın.
10 ve "10" değerlerinin tiplerini karşılaştırın — ikisi de aynı mı?
"""

tamsayi=10
ondaliksayi=2.3
yazi="Eren"
boolean=True
print(type(tamsayi))
print(type(ondaliksayi))
print(type(yazi))
print(type(boolean))
print("--------")
print(type(10))
print(type("10"))

"""
SORU-5
Temel Matematik İşlemleri
15 ve 4 sayılarını kullanarak toplama, çıkarma, çarpma ve bölme işlemlerini yapın.
17'nin 5'e bölümünden kalanı (mod) bulun.
2'nin 8. kuvvetini (2 üzeri 😄 hesaplayın.
"""
toplama=15+4
cikarma=15-4
carpma=15*4
bolme=15/4

modBulma=17%5

kvvet=2**8

print(toplama)
print(cikarma)
print(carpma)
print(bolme)
print(modBulma)
print(kvvet)

"""
SORU-6
Kullanıcıdan Veri Alma (input)
Kullanıcıdan adını alıp "Merhaba, [ad]!" şeklinde yazdıran bir program yazın.
Kullanıcıdan yaşını alıp 10 yıl sonraki yaşını hesaplayıp yazdıran bir program yazın
"""
isim=input("İsminizi Girin:")
print(f"Merhaba,[{isim}!]")
yas=int(input("Yaşınızı Girin:"))
yeni_yas=yas+10
print(f"10 yıl sonrakı Yaşınız[{yeni_yas}]")

"""
SORU-7
Karşılaştırma Operatörleri
a = 8, b = 12 için a > b, a < b ve a == b sonuçlarını yazdırın.
Kullanıcıdan bir sayı alıp bu sayının 100'e eşit olup olmadığını kontrol edin.
"""
a=8
b=12
print(a>b,a<b,a==b)

sayi=int(input("Sayı Girin:"))
print(sayi==100)

"""
SORU-8
Mantıksal Operatörler
yas = 22 ve ogrenci_mi = False değişkenleri için and, or ve not sonuçlarını yazdırın.
Bir kişinin hem 18 yaşından büyük hem de kayıtlı olup olmadığını kontrol eden bir ifade yazın.
"""
yas=22
ogrenci_mi=False

print(yas>18 and ogrenci_mi)
print(yas>18 or ogrenci_mi)
print(not ogrenci_mi)

yas=20
kayitli_mi=True
sonuc=(yas>18 and kayitli_mi)
print(sonuc)

"""
SORU-9
Basit if-else Kullanımı
Kullanıcıdan bir sayı alıp bu sayının pozitif mi negatif mi olduğunu yazdıran bir program yazın.
Kullanıcıdan not alıp 50 ve üzeri ise "Geçti", altında ise "Kaldı" yazdıran bir program yazın.
"""
sayi=int(input("Sayı Girin:"))
if(sayi<0):
    print("Negatif Sayı")
elif(sayi==0):
    print("Sıfır")
else:
    print("Pozitif Sayı")



ders_notu=int(input("Notunuzu gırınız:"))
if(ders_notu>50):
    print("Geçtiniz")
else:
    print("Kaldınız")

"""
SORU-10
String (Yazı) ile Temel İşlemler
Adınızı ve soyadınızı ayrı değişkenlerde tutup birleştirerek tam adınızı yazdırın.
Bir kelimenin kaç harften oluştuğunu len() ile bulun.
Bir yazıyı tamamen büyük harfe, sonra tamamen küçük harfe çevirin.
"""
isim="Eren"
soyisim="Altun"
print(isim+" "+soyisim)
print(len(isim))
buyutme=isim.upper()
print(buyutme)
kucultme=isim.lower()
print(kucultme)

"""
SORU-11
Basit Bir Program Örneği
Kullanıcıdan iki sayı alıp çarpımını yazdıran bir program yazın.
Kullanıcıdan bir sayı alıp bu sayının karesini (kendisiyle çarpımını) hesaplayan bir program yazın.
"""
sayi1=int(input("Sayı 1 Girin:"))
sayi2=int(input("Sayı 2 Girin:"))
print("Cevap",sayi1*sayi2)

sayi3=int(input("Sayı Girin:"))
print("Cevap",sayi3**2)

"""# **DERS-iÇERİĞİ**

"""

def kare_al(sayi):
  sonuc=sayi**2
  return sonuc

kare_al(10)

def selamlar (isim):
  print(f"Merhaba {isim}")

selamlar("hasan")

def cift_mi (sayi):
  if sayi %2==0:
    return True
  else:
    return False

print(cift_mi(10))

def buyuk_kucuk (a,b):
  if a>b:
    return f"{a} daha büyük"
  elif a<b:
    return f"{b} daha büyük"
  else:
    return f"{a} ve {b} eşit "

buyuk_kucuk(6,6)

ders_sayisi=int(input("Kaç ders aldınız: "))
notlar=[]

for i in range(ders_sayisi):
  nots=float(input(f"{i+1}.ders notunu giriniz: "))
  notlar.append(nots)

ortalama = sum(notlar)/len(notlar)
print(f"Ortalamanız: {ortalama}")

if ortalama >= 60:
  print("Başarılısınız")
else:
  print("Başarısızsınız")

sepet = []
toplam_fiyat=[]

for i in range (4):
  urun = input("Ürün Adı Girin: ")
  fiyat = float(input("Ürün Fiyatı Girin: "))
  sepet.append(urun)
  toplam_fiyat.append(fiyat)
print("\n--- Sepetiniz")
for urun in sepet:
  print("-",urun)
print("\nToplam Fiyat: ",sum(toplam_fiyat))

"""# **CASE-2**

"""

"""
SORU-1
Değişkenlerle Basit Hesaplamalar
* Toplam Tutar: Bir ürünün birim fiyatını ve adedini değişkenlerde tutup toplam tutarı hesaplayın.
* Maaş Artışı: maas değişkenine 8000 değeri verin; ardından += ile 1500 TL zam ekleyip yeni maaşı yazdırın.
"""
urun_fiyat=10
adet=5
toplam_tutar=urun_fiyat*adet
print(toplam_tutar)

maas=8000
maas+=1500
print(maas)

"""
SORU-2
2. İç İçe (Nested) if-else
* Bilet Ücreti: Kullanıcıdan yaş ve öğrencilik durumu alın:
65 yaş üstü: "Ücretsiz"
Öğrenci: "İndirimli"
Diğer: "Tam ücret"
* Sayı Denetimi: Bir sayının hem pozitif hem de çift olup olmadığını iç içe if ile kontrol edin.
"""
yas=int(input("yasınız nedir :"))
ogrenci_mi=int(input("Öğrenci misiniz: 0-Hayır 1-Evet"))

if(yas>=65):
  print("Ücretsiz")
elif(ogrenci_mi==1):
  print("İndirimli")
else:
  print("Tam Ücret")

sayi=int(input("sayi giriniz: "))
if sayi >= 0 :
    if sayi % 2 == 0:
      print("sayı çifttir ve pozitiftir")
    else:
      print("sayı tektir ve pozitiftir")
else:
    print("sayı negatiftir")

"""
SORU-3
elif ile Çoklu Koşullar
* Hava Durumu: Sıcaklık değerine göre;

30 üstü: "Sıcak"

15-30 arası: "Ilıman"

15 altı: "Soğuk"
* Mevsim Bulma: 1-12 arası girilen ay numarasına göre mevsimi elif ile belirleyin.
"""
derece=int(input("hava sıcaklıgını gırınız: "))
if derece>30:
  print("Sıcak")
elif derece>15:
  print("Ilıman")
else:
  print("soguk")


ay_numarası = int(input("ay numarası giriniz: "))

if ay_numarası == 1:
    print("Ocak")
elif ay_numarası == 2:
    print("Şubat")
elif ay_numarası == 3:
    print("Mart")
elif ay_numarası == 4:
    print("Nisan")
elif ay_numarası == 5:
    print("Mayıs")
elif ay_numarası == 6:
    print("Haziran")
elif ay_numarası == 7:
    print("Temmuz")
elif ay_numarası == 8:
    print("Ağustos")
elif ay_numarası == 9:
    print("Eylül")
elif ay_numarası == 10:
    print("Ekim")
elif ay_numarası == 11:
    print("Kasım")
elif ay_numarası == 12:
    print("Aralık")
else:
    print("Geçersiz ay numarası! (1-12 arasında bir sayı giriniz)")

"""
SORU-4
4. for Döngüsü ile Liste İşlemleri
* Maksimum Bulma: [5, 15, 8, 22, 3, 19] listesindeki en büyük sayıyı max() kullanmadan döngüyle bulun.
* Eşik Sayacı: Liste içindeki sayılardan kaç tanesinin 10'dan büyük olduğunu sayın.
"""
list=[5,15,8,22,3,19]
max_sayi=list[0]
for i in list:
  if max_sayi < i:
    max_sayi=i
print(max_sayi)

counter=0
for i in list:
  if i>10:
    counter+=1

print(counter)

"""
SORU-5
5. while Döngüsü ile Basit Sayaç
* Geri Sayım: 10'dan 1'e doğru geri sayan bir döngü kurun.
* Şifre Kontrolü: Doğru şifre girilene kadar kullanıcıya tekrar tekrar şifre soran program yazın.
"""
sayac=10
while sayac>=1 :
  print(sayac)
  sayac-=1


sifre=2011
giris=int(input("şifre giriniz: "))
while sifre != giris:
  print("şifre yanlış")
  giris=int(input("şifre giriniz: "))
print("şifre doğru")

"""
SORU-6
6. Döngü İçinde Koşul Kullanma
* 3'e Bölünenler: 1'den 20'ye kadar olan sayılardan sadece 3'e bölünenleri yazdırın.
* İşaret Ayrıştırma: Karışık listedeki negatif ve pozitif sayıları iki ayrı listeye ayırıp yazdırın.
"""
for i in range (1,21):
  if i%3==0:
    print(i)

liste= [5,1,15,86,-1,-45,-69]
pozitif_liste=[]
negatif_liste=[]
for i in liste:
  if i>0:
    pozitif_liste.append(i)
  else:
    negatif_liste.append(i)
print(pozitif_liste)
print(negatif_liste)

"""
SORU-7
7. Basit Fonksiyon Tanımlama
* Küp Alma: Sayının küpünü hesaplayan kup_al() fonksiyonunu yazın.
* Toplama: İki sayıyı parametre alıp toplamını döndüren fonksiyon yazın.
"""
def kup_al(sayi):
  sonuc=sayi**3
  return sonuc
print(kup_al(3))

def toplam(a,b):
  sonuc=a+b
  return sonuc
print(toplam(2,3))

"""
SORU-8
8. Fonksiyon + Koşul Birlikte
* Durum Kontrolü: Sayının pozitif, negatif veya sıfır olduğunu metin olarak döndüren sayi_durumu() fonksiyonunu yazın.
* En Büyüğü Bulma: Üç sayı arasından en büyüğünü döndüren fonksiyon yazın.
"""
def sayi_durumu(sayi):
  if sayi>0:
    return "Pozitif"
  elif sayi==0:
    return "Sıfırdır"
  else:
    return "negatiftir"
print(sayi_durumu(-21))

"""
SORU-8-PART-2
"""
def en_buyuk(a,b,c):
  liste=[a,b,c]
  maxi=liste[0]
  for i in liste:
    if maxi < i :
      maxi=i
  return maxi
print(en_buyuk(1,2,3))

"""
SORU-9
9. Liste Oluşturma ve İşleme
* Şehir Listesi: Boş listeye kullanıcıdan 5 şehir alıp ekleyin; listeyi numaralandırarak (1, 2, 3...) yazdırın.
* Ürün Silme: Ürün listesinden istenilen bir ürünü .remove() ile çıkarıp güncel listeyi gösterin.
"""
liste=[]
for i in range (5):
  sehir=str(input("sehir giriniz: "))
  liste.append(sehir)
for sayi,sehir in enumerate (liste):
  print(sayi+1,sehir)

"""
SORU-9-PART-2
"""
liste=[]
for i in range (5):
  urun=str(input("urun giriniz: "))
  liste.append(urun)
silinecek = str(input("silinecek urunu giriniz: "))
liste.remove(silinecek)
print(liste)

"""
SORU-10
10. Kullanıcıdan Birden Fazla Veri Alma
* Yaş Hesaplama: Ad, soyad ve doğum yılı alıp 2026 yılına göre yaş hesaplayın.
* BMI (VKİ) Hesaplama: Boy (cm) ve kilo alarak vücut kitle indeksini hesaplayın.
"""
ad=str(input("adınızı giriniz: "))
soyad=str(input("soyadınızı giriniz: "))
dogum_yili=int(input("dogum yilini giriniz: "))
yas=2026-dogum_yili
print(ad,soyad,yas)

"""
SORU-10-PART-2
"""
boy=float(input("boyunuzu m cinsinden giriniz: "))
kilo=float(input("kilonuzu giriniz: "))
bmı=kilo/boy**2
print(bmı)

"""
SORU-11
11. Uygulama: Not Ortalaması
* Harf Notu: 4 dersin notunu alıp ortalamayı harf notuna (AA, BA, BB...) çevirin.
* Uç Değerler: En yüksek ve en düşük notları ekrana yazdırın.
"""
#del max # yukarıdakı sorularda max dıye tanımlama yaptım o yuzden ordakı kalan seylerı sılmek ıcın kullanıyorum del'ı
del min
#soru 11
notlar = []

for i in range(4):
    notu = int(input("not giriniz: "))
    notlar.append(notu)

ortalama = sum(notlar) / len(notlar)
max_sayi=max(notlar)
min_sayi=min(notlar)
print(ortalama)
print(max_sayi)
print(min_sayi)

"""
SORU-12
12. Uygulama: Basit Sepet
* Filtreleme: Sepetteki 100 TL üzeri ürünleri ayrı bir listede toplayın.
* İndirim: Toplam sepet 500 TL'yi aşarsa "%10 indirim kazandınız" uyarısı verip yeni tutarı hesaplayın.
"""
sepet=[]
PahalıSepet=[]
toplam_fiyat=0
for i in range (4):
  urun=str(input("ürün giriniz: "))
  sepet.append(urun)
  fiyat=int(input("fiyat giriniz: "))
  toplam_fiyat+=fiyat
  if fiyat>100:
    PahalıSepet.append(urun)
if toplam_fiyat>500:
  print("10% indirim kazandınız");
print("100TL ve üzeri olan urunler",PahalıSepet)

"""# **DERS ANLATIM**"""

def selamlar (isim,mesaj="Merhaba"):
  print(f"{mesaj} {isim}")

selamlar("hasan")
selamlar("eren","iyi günler")
selamlar(isim="berykay",mesaj="deneme")

def toplam_hesapla(*sayilar):   # * args ıstedıgımız kadar arguman gondermemızı saglar
  toplam=0
  for sayi in sayilar:
    toplam+=sayi
  return toplam

print(toplam_hesapla(1,2,3,4,5))

def profil_olustur(**bilgiler):   # ** fonksıyona anahtar deger atamayı saglar
  for anahtar,deger in bilgiler.items():
    print(f"{anahtar}: {deger}")

profil_olustur(ad="Eren",soyad="Altun",yas=22)

sayilar = [1,2,3,4,5,6,7,8,9,10]

kareler=[x**2 for x in sayilar]
print(kareler)

ciftler=[x for x in sayilar if x%2==0]
print(ciftler)

etiketler = ["Çift" if x%2==0 else "Tek" for x in sayilar]
print(etiketler)

"""# **CLASS-KONUSU-DERS-ANLATIMI**



"""

class ogrenci:
  def __init__(self,isim,yas,notlar):
     self.isim=isim
     self.yas= yas
     self.notlar=notlar

     def ortalama_hesapla(self):
        return sum(self.notlar)/len(self.notlar)

     def durum(self):
        ortalama=self.ortalama_hesapla()
        return "Geçti" if ortalama>=60 else "Kaldı"

ogrenci1=ogrenci("Eren",22,[80,90,70])

import random
zar = random.randint(1,6)
print(f"zar sonucu: {zar}")

"""# **CASE-3-CLASS-OLUSTURMA**:"""

# ARABA SINIFI
"""
SORU-1
marka, model ve hiz (km/s) bilgilerini tutan bir Araba sınıfı oluşturun.
hızlandır(artis) metodu ile hızı artırın.
bilgi_goster() metodu ile araç bilgilerini yazdırın.
"""
class araba:
  def __init__ (self,marka,model,hiz):
    self.marka=marka
    self.model=model
    self.hiz=hiz

  def hizlandir(self):
    return self.hiz+5

  def bilgi_goster(self):
    return print(self.marka,self.model,self.hiz)

araba1=araba("Hyundai","i20",110)
araba1.bilgi_goster()
araba1.hizlandir()

"""
SORU-2
uzunluk ve genislik bilgilerini tutan bir Dikdortgen sınıfı oluşturun.
alan_hesapla() metodu ile alanı hesaplayın (uzunluk * genislik).
cevre_hesapla() metodu ile çevreyi hesaplayın (2 * (uzunluk + genislik)).
"""
class dikdortgen:
  def __init__(self,uzunluk,genislik):
    self.uzunluk=uzunluk
    self.genislik=genislik

  def alan_hesapla(self):
    return self.uzunluk*self.genislik

  def cevre_hesapla(self):
    return (self.uzunluk+self.genislik)*2

dikdortgen1=dikdortgen(10,5)
print(dikdortgen1.alan_hesapla())
print(dikdortgen1.cevre_hesapla())

"""
SORU-3
ad, yazar ve sayfa_sayisi bilgilerini tutan bir Kitap sınıfı oluşturun.
ozet() metodu ile "Suç ve Ceza - Dostoyevski (671 sayfa)" formatında bilgi döndürün.
"""

class kitap:
  def __init__(self,ad,yazar,sayfa_sayisi):
     self.ad=ad
     self.yazar=yazar
     self.sayfa_sayisi=sayfa_sayisi

  def ozet(self):
    return print(self.ad,self.yazar,f"({self.sayfa_sayisi} sayfa)")

kitap1=kitap("Yaban","Yakup Kadri Karaosmanoğlu",214)
kitap1.ozet()

class Urun:
  def __init__(self,isim,fiyat,stok_adedi):
    self.isim=isim
    self.fiyat=fiyat
    self.stok_adedi=stok_adedi

  def toplam_hesapla(self):
    return self.fiyat*self.stok_adedi

  def stok_durum(self):
    if self.stok_adedi==0:
      return "Tükendi"
    elif self.stok_adedi <10:
      return "Stok Azalmış"
    else:
      return "yeterlı stok"

urun1=Urun("elma",23,10)
print(urun1.toplam_hesapla())
print(urun1.stok_durum())

